language: ruby
rvm:
  - 1.8.7
  - 1.9.2
  - 1.9.3
env:
  - DB=sqlite
  - DB=postgresql
script:
  - RAILS_ENV=test bundle exec rake --trace db:migrate spec
before_script:
  - psql -c 'create database myapp_test' -U postgres
